set backspace=2
set cmdheight=2
set colorcolumn=80
set expandtab
set exrc
set guicursor=
set hidden
set ignorecase
set incsearch
set laststatus=2
set laststatus=2
set nobackup
set noerrorbells
set nohlsearch
set noswapfile
set number
set relativenumber
set scrolloff=8
set shiftround
set shiftwidth=4
set showcmd
set showmatch
set signcolumn=yes
set smartcase
set smartindent
set tabstop=4 softtabstop=4
set undodir=~/.vim/undodir
set undofile
